server:
  port: 8100
spring:
  cloud:
    nacos:
      discovery:
        enabled: true
        group: hf-basic
        username: nacos
        password: nacos
        register-enabled: true
        #nacos??
        server-addr: 127.0.0.1:8848
        #????
        service: file-system


  application:
    name: file-system
  datasource:
    url: jdbc:mysql://localhost:3306/hfbasic?useUnicode=true&characterEncoding=utf8&userSSL=false
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: hf296829
mybatis:
  mapper-locations: classpath:mapping/*mapper.xml # Mybatis ??????
  type-aliases-package: com.hf.basic.entity  # ????????

minio:
  url: http://218.245.99.248:9001
  accessKey: minio
  secretKey: minio@2022
  bucketName: application
#  accessKey: WVUFGGENPVSPEDBS1521
#  secretKey: Bco1MoAi2+7k89BG1kmA+x8YrZqYlO1Bx1uVRM3t